### ISSUE TITLE
"stable" tag points to broken version

### ISSUE THREAD

**Issue by cr** [mozmark/OneCRL-Tools#40]
I finally came round to switching TLS Canary over to the brand new *stable* tag, just to find that it points to a broken commit b7bc37cb6a5.

```
# github.com/mozmark/OneCRL-Tools/oneCRL2RevocationsTxt
../../.tlscanary/go/src/github.com/mozmark/OneCRL-Tools/oneCRL2RevocationsTxt/main.go:51: multiple-value config.GetRecordURL() in single-value context
```

TLS Canary has been successfully using commit 244e704 in production for a while now. @mozmark, please point your *stable* tag to that commit as soon as possible, and leave it there until you can find a later commit that is **verified** to work.

**Comment by cr** [comment]
Essentially all you need to do is

```
git tag -f stable 244e704 
git push origin refs/tags/stable --force
```

Replace `stable` in the *push * command with `refs/tags/stable` if you also have an unpublished  branch of that same name.

**Comment by mozmark** [comment]
Did that fix it?

**Comment by cr** [comment]
Yes, thanks!
